#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirement

cp /etc/hosts ~/hosts.new
sed -i 's/^127.*$/127.0.0.2 localhost' -e '$a\8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
